# Generated by Django 5.0.6 on 2024-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='button_name',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
