# Generated by Django 5.0.6 on 2024-06-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testemonialsitems',
            options={'verbose_name': 'Testemonial Items', 'verbose_name_plural': 'Testemonials Items'},
        ),
    ]
