# Generated by Django 5.0.6 on 2024-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_testemonialsitems_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='button_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
