# Generated by Django 5.0.6 on 2024-06-27 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_button_name_team_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='newideasitems',
            name='short',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
