# Generated by Django 5.0.6 on 2024-06-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testemonial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=155)),
                ('image', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('short', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('buttom_name', models.CharField(max_length=65)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Item',
                'verbose_name_plural': 'Blog Items',
            },
        ),
    ]
