# Generated by Django 5.0.6 on 2024-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitems',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
