# Generated by Django 5.0.6 on 2024-06-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_menu', models.BooleanField(default=True)),
                ('show_header', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_carousel', models.BooleanField(default=True)),
                ('show_team', models.BooleanField(default=True)),
                ('show_services', models.BooleanField(default=True)),
                ('show_new_ideas', models.BooleanField(default=True)),
                ('show_testemonial', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('show_newsletter', models.BooleanField(default=True)),
                ('show_socials', models.BooleanField(default=True)),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/%y/%m/%d')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%y/%m/%d')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='logos/%y/%m/%d')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('x_twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setup',
                'verbose_name_plural': 'Site Setups',
            },
        ),
    ]
